### PR TITLE
Medium level | #75 | 24ms

### PR DESCRIPTION
**Pull request by DeepakR-28**
Leetcode medium level question, faster than 92% and memory usage is better than 99.99% of all python solutions.
problem number 75 python solution

### CODE REVIEW

**Comment by miichack** [comment]
Can you add the required comment in the file, which is described in the readme file? I will then merge your PR

**Comment by DeepakR-28** [comment]
Are the changes alright?

**Comment by miichack** [comment]
It was still missing the link, but I will add it manually myself as I have some time now

**Comment by DeepakR-28** [comment]
Thank you :) 👍 😄

**Comment by miichack** [comment]
You are welcome :)

**Pull request merged**
